# docker-compose.yml
version: "3.8"

services:
  bot:
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=telegram_premium_bot

volumes:
  mongodb_data: